services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio-safe-demo
    ports:
      - "4873:4873"
    volumes:
      - ./infra/verdaccio/config.yaml:/verdaccio/conf/config.yaml
      - verdaccio_storage:/verdaccio/storage
    networks:
      poc_network:
        ipv4_address: 172.30.0.10

  attacker:
    build: ./attacker-server
    container_name: attacker-receiver
    ports:
      - "8080:8080"
    volumes:
      - ./attacker-server/loot:/app/loot
    networks:
      poc_network:
        ipv4_address: 172.30.0.20

networks:
  poc_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  verdaccio_storage:
